### ISSUE TITLE
Fails to load component

### ISSUE THREAD

**Issue by scooby359** [React-Component-Preview/react-preview-extension#29]
When trying to run the extension and preview a component, displays an error that the previewConfiguration.json file cannot be found. Looks like it's attempting to access the wrong folder - `C:\c:\..`

![image](https://user-images.githubusercontent.com/17240654/191697645-7af4245e-a432-45a9-8d6c-2afe321db9df.png)

**Comment by unwls** [comment]
@scooby359 I'm assuming you are using the windows operating system? This extension only works on mac operating system for now.

**Comment by scooby359** [comment]
@unwls Ah yes, I'm on Windows. Just looked at the extension page in VS Code, realised it doesn't mention being Mac only until half way down the page. Maybe that could be made more prominent in the extension description.
